package(default_visibility = ['//visibility:public'])

load('@org_dropbox_rules_node//node:def.bzl', 'node_internal_module')

node_internal_module(
    name = 'internal_module',
    srcs = ['index.js'],
    main = 'index.js',
)
